"""create incidents table

Revision ID: 2859ba3c7f65
Revises: 
Create Date: 2026-06-27 00:47:46.148954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2859ba3c7f65'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('recovery_action', sa.String(length=32), nullable=False),
    sa.Column('execution_id', sa.String(length=36), nullable=True),
    sa.Column('thread_id', sa.String(length=255), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_acknowledged'), 'incidents', ['acknowledged'], unique=False)
    op.create_index(op.f('ix_incidents_category'), 'incidents', ['category'], unique=False)
    op.create_index(op.f('ix_incidents_execution_id'), 'incidents', ['execution_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incidents_execution_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_category'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_acknowledged'), table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###
